#include <iostream>
#include <string>
#include <iomanip>
#include <time.h>
#include <vector>
#include <fstream>
#include <sstream>
#include <list>
#include <algorithm>
#include <numeric>

using std::cout;
using std::cin;
using std::string;
using std::to_string;
using std::endl;
using std::left;
using std::setw;
using std::setfill;
using std::fixed;
using std::setprecision;
using std::vector;
using std::ofstream;
using std::ifstream;
using std::list;
using std::stringstream;